# -*- coding: utf-8 -*-
"""Makro ve piyasa göstergelerinin ortak kataloğu.

TradingView başlıkları, snapshot schema etiketleri ve doğrulama anahtarları
bu tek dosyadan beslenir. Bir gösterge burada tanımlanmadıkça rapora sayı giremez.
"""

# id, Türkçe etiket, varsayılan birim, TradingView başlıkları, frekans
GOSTERGE_TANIMLARI = [
    ("inflation_yoy", "Enflasyon (yıllık)", "%",
     ("inflation rate yoy", "inflation rate yoy final", "inflation rate yoy flash"), "aylık"),
    ("inflation_mom", "Enflasyon (aylık)", "%",
     ("inflation rate mom", "inflation rate mom final", "inflation rate mom flash"), "aylık"),
    ("core_inflation_yoy", "Çekirdek Enflasyon (yıllık)", "%",
     ("core inflation rate yoy", "core inflation rate yoy final", "core inflation rate yoy flash"), "aylık"),
    ("pce_inflation_yoy", "PCE Enflasyon (yıllık)", "%",
     ("pce price index yoy",), "aylık"),
    ("pce_inflation_mom", "PCE Enflasyon (aylık)", "%",
     ("pce price index mom",), "aylık"),
    ("core_pce_yoy", "Çekirdek PCE (yıllık)", "%",
     ("core pce price index yoy",), "aylık"),
    ("core_pce_mom", "Çekirdek PCE (aylık)", "%",
     ("core pce price index mom",), "aylık"),
    ("inflation_expectation_1y", "Enflasyon Beklentisi (1 yıl)", "%",
     ("michigan inflation expectations final", "consumer inflation expectations",
      "ecb consumer inflation expectations"), "aylık"),
    ("inflation_expectation_5y", "Enflasyon Beklentisi (5 yıl)", "%",
     ("michigan 5 year inflation expectations final",), "aylık"),
    ("producer_prices_yoy", "ÜFE (yıllık)", "%",
     ("producer prices", "producer prices yoy", "ppi yoy"), "aylık"),
    ("producer_prices_mom", "ÜFE (aylık)", "%",
     ("ppi mom", "producer prices mom"), "aylık"),
    ("policy_rate", "Politika faizi", "%",
     ("interest rate decision", "fed interest rate decision",
      "ecb interest rate decision", "tcmb interest rate decision"), "olay"),
    ("unemployment_rate", "İşsizlik oranı", "%",
     ("unemployment rate",), "aylık"),
    ("u6_unemployment", "Genişletilmiş İşsizlik (U-6)", "%",
     ("u-6 unemployment rate",), "aylık"),
    ("participation_rate", "Ekonomik Katılım Oranı", "%",
     ("participation rate",), "aylık"),
    ("nonfarm_payroll", "ABD İstihdam Değişimi (NFP)", "bin kişi",
     ("non farm payrolls",), "aylık"),
    ("wage_growth_yoy", "Ücret Artışı (yıllık)", "%",
     ("average hourly earnings yoy", "wage growth yoy", "negotiated wage growth"), "aylık"),
    ("wage_growth_mom", "Ücret Artışı (aylık)", "%",
     ("average hourly earnings mom",), "aylık"),
    ("industrial_production_yoy", "Sanayi Üretimi (yıllık)", "%",
     ("industrial production yoy",), "aylık"),
    ("industrial_production_mom", "Sanayi Üretimi (aylık)", "%",
     ("industrial production mom",), "aylık"),
    ("retail_sales_yoy", "Perakende Satış (yıllık)", "%",
     ("retail sales yoy",), "aylık"),
    ("retail_sales_mom", "Perakende Satış (aylık)", "%",
     ("retail sales mom",), "aylık"),
    ("pmi_manufacturing", "İmalat PMI", "puan",
     ("ism manufacturing pmi", "s&p global manufacturing pmi final",
      "s&p global manufacturing pmi flash", "chicago pmi",
      "istanbul chamber of industry manufacturing pmi"), "aylık"),
    ("pmi_services", "Hizmetler PMI", "puan",
     ("ism services pmi", "s&p global services pmi final",
      "s&p global services pmi flash"), "aylık"),
    ("pmi_composite", "Bileşik PMI", "puan",
     ("s&p global composite pmi final", "s&p global composite pmi flash"), "aylık"),
    ("consumer_confidence", "Tüketici Güveni", "puan",
     ("consumer confidence", "consumer confidence final", "consumer confidence flash",
      "cb consumer confidence"), "aylık"),
    ("business_confidence", "İş Güveni", "puan",
     ("business confidence",), "aylık"),
    ("economic_sentiment", "Ekonomik Beklenti Endeksi", "puan",
     ("economic sentiment", "economic confidence index"), "aylık"),
    ("growth_yoy", "Büyüme (yıllık)", "%",
     ("gdp growth rate yoy", "gdp growth rate yoy final",
      "gdp growth rate yoy flash", "gdp growth rate yoy 2nd est",
      "gdp growth rate yoy 3rd est"), "üç aylık"),
    ("growth_qoq", "Büyüme (çeyreklik)", "%",
     ("gdp growth rate qoq", "gdp growth rate qoq final",
      "gdp growth rate qoq flash", "gdp growth rate qoq 2nd est",
      "gdp growth rate qoq 3rd est"), "üç aylık"),
    ("current_account", "Cari denge", "",
     ("current account",), "üç aylık"),
    ("trade_balance", "Ticaret Dengesi", "",
     ("balance of trade", "balance of trade final", "balance of trade prel"), "aylık"),
    ("exports", "İhracat", "", ("exports", "exports final", "exports prel"), "aylık"),
    ("imports", "İthalat", "", ("imports", "imports final", "imports prel"), "aylık"),
    ("budget_balance", "Bütçe Dengesi", "",
     ("budget balance",), "aylık"),
    ("budget_gdp", "Bütçe / GSYH", "%",
     ("government budget to gdp",), "yıllık"),
    ("fx_reserves", "Döviz rezervleri", "",
     ("foreign exchange reserves",), "haftalık"),
    ("m3_yoy", "M3 Para Arzı (yıllık)", "%",
     ("m3 money supply yoy",), "aylık"),
    ("consumer_credit", "Tüketici Kredisi Değişimi", "%",
     ("consumer credit change",), "aylık"),
    ("initial_jobless_claims", "İlk İşsizlik Başvurusu", "bin kişi",
     ("initial jobless claims",), "haftalık"),
    ("continuing_jobless_claims", "Devam Eden İşsizlik Başvurusu", "bin kişi",
     ("continuing jobless claims",), "haftalık"),
    ("job_openings", "JOLTs Açık İş Sayısı", "milyon kişi",
     ("jolts job openings",), "aylık"),
    ("new_home_sales", "Yeni Konut Satışları", "milyon adet",
     ("new home sales",), "aylık"),
    ("durable_goods", "Dayanıklı Mal Siparişleri (aylık)", "%",
     ("durable goods orders mom",), "aylık"),
    # --- Genisletilmis makro bloglari (TV basliklari dogrulanmis) ---
    ("tourism_revenues", "Turizm Gelirleri", "",
     ("tourism revenues",), "üç aylık"),
    ("tourist_arrivals_yoy", "Turist Sayısı (yıllık)", "%",
     ("tourist arrivals yoy",), "aylık"),
    ("capacity_utilization", "Kapasite Kullanım Oranı", "%",
     ("capacity utilization",), "aylık"),
    ("debt_gdp", "Borç / GSYH", "%",
     ("government debt to gdp",), "yıllık"),
    ("loans_companies_yoy", "Şirketlere Krediler (yıllık)", "%",
     ("loans to companies yoy",), "aylık"),
    ("loans_households_yoy", "Hanehalkına Krediler (yıllık)", "%",
     ("loans to households yoy",), "aylık"),
    ("consumer_spending_qoq", "Tüketici Harcamaları (çeyreklik)", "%",
     ("real consumer spending qoq adv", "real consumer spending qoq"), "üç aylık"),
    ("rate_projection_1y", "Faiz Projeksiyonu (1. yıl)", "%",
     ("interest rate projection - 1st yr",), "üç aylık"),
    ("rate_projection_2y", "Faiz Projeksiyonu (2. yıl)", "%",
     ("interest rate projection - 2nd yr",), "üç aylık"),
    # --- EVDS akilli (TV'de karsiligi yok; evds_veri.py doldurur) ---
    ("deposit_rate", "Mevduat Faizi", "%", (), "aylık"),
    ("consumer_loan_rate", "Tüketici Kredisi Faizi", "%", (), "aylık"),
    ("credit_growth_yoy", "Kredi Büyümesi (yıllık)", "%", (), "aylık"),
    ("reer", "Reel Efektif Döviz Kuru", "", (), "aylık"),
]

GOSTERGE_KOD = {item[1]: item[0] for item in GOSTERGE_TANIMLARI}
KOD_GOSTERGE = {item[0]: item for item in GOSTERGE_TANIMLARI}

# Akşam snapshot'ında bulunması hedeflenen piyasa serileri. Bazıları
# yayınlanmazsa rapor bunları atlar; sıfır/placeholder üretilmez.
PIYASA_SERILERI = (
    ("USDTRY=X", "usdtry", "USD/TRY", "TL", "FX"),
    ("EURTRY=X", "eurtry", "EUR/TRY", "TL", "FX"),
    ("GC=F", "gold_usd", "Altın", "USD/ons", "emtia"),
    ("CL=F", "wti", "WTI Petrol", "USD/varil", "emtia"),
    ("BZ=F", "brent", "Brent Petrol", "USD/varil", "emtia"),
    ("DX-Y.NYB", "dxy", "DXY", "indeks", "küresel risk"),
    ("^VIX", "vix", "VIX", "indeks", "küresel risk"),
    ("^IRX", "ust3m", "ABD 3 Aylık Tahvil", "%", "faiz"),
    ("^FVX", "ust5y", "ABD 5 Yıllık Tahvil", "%", "faiz"),
    ("^TYX", "ust30y", "ABD 30 Yıllık Tahvil", "%", "faiz"),
)

PIYASA_KOD = {item[1] for item in PIYASA_SERILERI} | {
    "gold_try", "ust2y", "ust10y", "bist30", "bist100",
    # FRED kredi marjlari (BAMLC0A0CM / BAMLH0A0HYM2)
    "corp_oas", "hy_oas",
}

REQUIRED = {
    "TR": {"inflation_yoy", "policy_rate", "growth_yoy", "unemployment_rate",
           "current_account", "fx_reserves"},
    "US": {"inflation_yoy", "policy_rate", "growth_yoy", "unemployment_rate",
           "current_account"},
    "EU": {"inflation_yoy", "policy_rate", "growth_yoy", "unemployment_rate",
           "current_account"},
}
