name: WF Test Cron0
on:
  schedule:
    - cron: '30 14 * * 0'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo ok
